version: "3"
services:
  maze-wars:
    build:
      context: ..
      dockerfile: docker/Dockerfile.maze-wars.dev
    ports:
      #- '5555:5555'
      - '4000:4000'
    environment:
      - PORT=4000
