version: "3"
services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy:0.9.1
    container_name: nginx-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - letsencrypt-certs:/etc/nginx/certs
      - letsencrypt-vhost-d:/etc/nginx/vhost.d
      - letsencrypt-html:/usr/share/nginx/html
    networks:
      maze-wars:
    restart: always

  letsencrypt-proxy:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - letsencrypt-certs:/etc/nginx/certs
      - letsencrypt-vhost-d:/etc/nginx/vhost.d
      - letsencrypt-html:/usr/share/nginx/html
    environment:
      - NGINX_PROXY_CONTAINER=nginx-proxy
    networks:
      maze-wars:
    restart: always

  maze-wars:
    build:
      context: ..
      dockerfile: docker/Dockerfile.maze-wars.prod
      args:
        VERSION: ${VERSION}
    expose:
      - 3000
    environment:
      - PORT=3000
      - VIRTUAL_HOST=maze-wars.com,www.maze-wars.com
      - LETSENCRYPT_HOST=maze-wars.com,www.maze-wars.com
      - LETSENCRYPT_EMAIL=xescugil@gmail.com
    restart: on-failure


  # Metrics
  grafana:
    image: grafana/grafana:10.3.0
    user: "472"
    depends_on:
      - prometheus
    expose:
      - 3000
    volumes:
      - grafana_data:/var/lib/grafana
      - /home/maze-wars/grafana/provisioning/:/etc/grafana/provisioning/
    env_file:
      - ./data/grafana/config.monitoring
    networks:
      maze-wars:
    restart: always
    environment:
      - PORT=3000
      - VIRTUAL_HOST=metrics.maze-wars.com
      - LETSENCRYPT_HOST=metrics.maze-wars.com
      - LETSENCRYPT_EMAIL=xescugil@gmail.com

  prometheus:
    image: prom/prometheus:v2.36.2
    volumes:
      - /home/maze-wars/prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    expose:
      - 9090
    links:
      - cadvisor:cadvisor
    depends_on:
      - cadvisor
    networks:
      maze-wars:
    restart: always

  node-exporter:
    image: quay.io/prometheus/node-exporter:v1.7.0
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
      - /:/host:ro,rslave
    command: 
      - '--path.rootfs=/host'
      - '--path.procfs=/host/proc' 
      - '--path.sysfs=/host/sys'
      - --collector.filesystem.ignored-mount-points
      - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"
    expose:
      - 9100
    networks:
      maze-wars:
    restart: always

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:v0.47.2
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    expose:
      - 8080
    networks:
      maze-wars:
    restart: always

volumes:
  letsencrypt-certs:
  letsencrypt-vhost-d:
  letsencrypt-html:
  prometheus_data:
  grafana_data:

